using System.Text.Json.Serialization;

using Azure.AI.OpenAI;

namespace AzureOpenAIProxy.ApiApp.Models;

/// <summary> A single, role-attributed message within a chat completion interaction. </summary>
public class ChatMessageModel
{
    public ChatMessageModel()
    {
    }

    public ChatMessageModel(ChatMessage message)
    {
        this.Role = message.Role.ToString();
        this.Content = message.Content;
        this.Name = message.Name;
        this.FunctionCall = message.FunctionCall is null ? null : new FunctionCallModel(message.FunctionCall);
        this.AzureExtensionsContext = message.AzureExtensionsContext is null ? null : new AzureChatExtensionsMessageContextModel(message.AzureExtensionsContext);
    }

    /// <summary> The role associated with this message payload. </summary>
    [JsonPropertyName("role")]
    public string Role { get; set; }

    /// <summary> The text associated with this message payload. </summary>
    [JsonPropertyName("content")]
    public string Content { get; set; }

    /// <summary>
    /// The name of the author of this message. `name` is required if role is `function`, and it should be the name of the
    /// function whose response is in the `content`. May contain a-z, A-Z, 0-9, and underscores, with a maximum length of
    /// 64 characters.
    /// </summary>
    [JsonPropertyName("name")]
    public string Name { get; set; }

    /// <summary> The name and arguments of a function that should be called, as generated by the model. </summary>
    [JsonPropertyName("function_call")]
    public FunctionCallModel FunctionCall { get; set; }

    /// <summary>
    ///   Additional context data associated with a chat message when requesting chat completions using compatible Azure
    ///   OpenAI chat extensions. This includes information like the intermediate data source retrievals used to service a
    ///   request.
    ///   This context information is only populated when using Azure OpenAI with chat extensions capabilities configured.
    /// </summary>
    [JsonPropertyName("context")]
    public AzureChatExtensionsMessageContextModel AzureExtensionsContext { get; set; }
}
