name: Azure Dev - Build Only

on:
  push:
    branches:
    - 'feature/*'
    # paths-ignore:
    # - '.github/**'
  pull_request:
    branches:
    - main

permissions:
  id-token: write
  contents: read
  issues: write
  pull-requests: write

jobs:
  build-test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x

    - name: Install local certs
      shell: pwsh
      run: |
        dotnet tool update -g linux-dev-certs
        dotnet linux-dev-certs install

    - name: Install Aspire workload
      shell: pwsh
      run: |
        dotnet workload update
        dotnet workload install aspire

    - name: Restore NuGet packages
      shell: bash
      run: |
        dotnet restore

    - name: Build solution
      shell: bash
      run: |
        dotnet build

    - name: Test solution
      shell: bash
      run: |
        dotnet test --logger "trx" --collect:"XPlat Code Coverage"

    - name: Publish test results
      id: test-report
      uses: bibipkins/dotnet-test-reporter@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        results-path: ./**/TestResults/**/*.trx
        coverage-path: ./**/TestResults/**/*.xml
        coverage-type: cobertura
        coverage-threshold: 0
        # coverage-threshold: 80
        allow-failed-tests: true
        post-new-comment: true
        comment-title: "Test Results"

    - name: Comment to issue
      if: ${{ !cancelled() && github.event_name == 'pull_request' }}
      uses: actions-cool/issues-helper@v3
      with:
        actions: "create-comment"
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          ## Test Results

          ### Tests

          | :clipboard: Total | :heavy_check_mark: Passed | :x: Failed | :warning: Skipped |
          |-------------------|---------------------------|------------|-------------------|
          | ${{ steps.test-report.outputs.tests-total }} | ${{ steps.test-report.outputs.tests-passed }} | ${{ steps.test-report.outputs.tests-failed }} | ${{ steps.test-report.outputs.tests-skipped }} |

          ### Coverage

          | :straight_ruler: Line | :herb: Branch |
          |-----------------------|---------------|
          | ${{ steps.test-report.outputs.coverage-lines-covered }}/${{ steps.test-report.outputs.coverage-lines-total }} (${{ steps.test-report.outputs.coverage-line }}%) | ${{ steps.test-report.outputs.coverage-branches-covered }}/${{ steps.test-report.outputs.coverage-branches-total }} (${{ steps.test-report.outputs.coverage-branch }}%) |
