name: Azure Dev - Build Only

on:
  push:
    branches:
    - 'feature/*'
    paths-ignore:
    - '.github/**'
  pull_request:
    branches:
    - main

permissions:
  id-token: write
  contents: read
  issues: write

jobs:
  build-test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x

    - name: Install local certs
      shell: pwsh
      run: |
        dotnet tool update -g linux-dev-certs
        dotnet linux-dev-certs install

    - name: Install Aspire workload
      shell: pwsh
      run: |
        dotnet workload update
        dotnet workload install aspire

    - name: Restore NuGet packages
      shell: bash
      run: |
        dotnet restore

    - name: Build solution
      shell: bash
      run: |
        dotnet build

    - name: Test solution
      shell: bash
      run: |
        dotnet test --logger "trx" --collect:"XPlat Code Coverage"

    - name: Publish test results
      uses: bibipkins/dotnet-test-reporter@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        results-path: ./**/TestResults/**/*.trx
        coverage-path: ./**/TestResults/**/*.xml
        coverage-type: cobertura
        coverage-threshold: 80
        allow-failed-tests: true
        post-new-comment: true
